#!/bin/bash -e

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

src_release=target/wasm32-unknown-unknown/release
dst=build

if [ ! -d "$dst" ]; then
  mkdir "$dst"
fi

cargo build --release
cp -r "$src_release"/rshook.wasm "$dst"/index.wasm

hook-cleaner "$dst"/index.wasm
guard-checker "$dst"/index.wasm
